const results = [
  {
    status: "cheapest",
    handLuggage: 5,
    baggage: 15,
    optionalBaggage: null,
    price: 7712,
    source: "Clickavia",
    companyFirst: "aeroflot",
    companySecond: null,
    isCharter: true,
    time: "5ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T03:45",
    isBack: true,
    backDepTime: "2019-09-21T05:00",
    backDesTime: "2019-10-04T15:00"
  },
  {
    status: "fastest",
    handLuggage: 10,
    baggage: 20,
    optionalBaggage: null,
    price: 2712,
    source: "Купибилет",
    companyFirst: "rossiya",
    companySecond: null,
    isCharter: true,
    time: "4ч30м",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: true,
    backDepTime: "2018-01-24T05:00",
    backDesTime: "2018-01-25T03:25"
  },
  {
    status: "best",
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "rossiya",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "rossiya",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: true,
    backDepTime: "2018-02-24T05:00",
    backDesTime: "2018-02-24T05:00"
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "aeroflot",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "s7",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "rossiya",
    companySecond: null,
    isCharter: true,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: true,
    backDepTime: "2018-02-24T05:00",
    backDesTime: "2018-02-24T05:00"
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "rossiya",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "2018-02-24T05:00",
    desTime: "2018-02-24T05:00",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  }
];

export default results;
