const results = [
  {
    handLuggage: 5,
    baggage: 15,
    optionalBaggage: null,
    price: 7712,
    source: "Clickavia",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: true,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: true,
    backDepTime: "10:35",
    backDesTime: "17:10"
  },
  {
    handLuggage: 10,
    baggage: 20,
    optionalBaggage: null,
    price: 25712,
    source: "Купибилет",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: true,
    departure: "Москва",
    destination: "Барселона",
    depTime: "10:05",
    desTime: "13:05",
    isBack: true,
    backDepTime: "00:35",
    backDesTime: "18:10"
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  }
];

export { results };
