const results = [
  {
    status: "cheapest",
    handLuggage: 5,
    baggage: 15,
    optionalBaggage: null,
    price: 7712,
    source: "Clickavia",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: true,
    time: "5ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: true,
    backDepTime: "10:35",
    backDesTime: "17:10"
  },
  {
    status: "fastest",
    handLuggage: 10,
    baggage: 20,
    optionalBaggage: null,
    price: 25712,
    source: "Купибилет",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: true,
    time: "4ч30м",
    departure: "Москва",
    destination: "Барселона",
    depTime: "10:05",
    desTime: "13:05",
    isBack: true,
    backDepTime: "00:35",
    backDesTime: "18:10"
  },
  {
    status: "best",
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: true,
    backDepTime: "01:00",
    backDesTime: "03:00"
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: true,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: true,
    backDepTime: "00:05",
    backDesTime: "02:05"
  },
  {
    handLuggage: 2,
    baggage: null,
    optionalBaggage: null,
    price: 500,
    source: "Агенство билетов",
    companyFirst: "Россия",
    companySecond: null,
    isCharter: false,
    time: "6ч",
    departure: "Москва",
    destination: "Барселона",
    depTime: "00:05",
    desTime: "03:05",
    isBack: false,
    backDepTime: null,
    backDesTime: null
  }
];

export { results };
